### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Stebalien** [florianlenz/go-libp2p-bootstrap#1]
Sorry for the late review, I've been on a work trip. Nice work!

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L9

We generally don't check-in gx paths to the source (for everything *except* go-ipfs itself for special reasons) as they need to change any time a dep is updated.

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L25

Should probably comment on what these mean (especially this variable).

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L145

This combine all errors into one (or just return one of them). (Convention)

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L145

Should take a context.

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L159-L176

Isn't this just going to end up being synchronous?

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L185

It would be more idiomatic to implement the `io.Closer` interface here (`Close() error`).

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L67

Calling this multiple times on every disconnect is going to be a bit slow (lots of copying). I'd recommend tracking connects and disconnects with a counter (although we might want to consider adding some kind of `Size()` method to the Network interface).

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L86

We definitely don't want to panic in cases like this.

---

https://github.com/florianlenz/go-libp2p-bootstrap/blob/4d1c241fcad66908eea39e6c89e54c895c062093/bootstrap.go#L207

This check isn't going to be thread-safe. This service should probably either use actual locks or have a dedicated bootstrapping state-machine goroutine.

---

General comment: writing to a variable from one thread and reading it from another without a lock is going to cause memory safety issues. You'll probably need to use a lock for, e.g. the `started` variable (and possibly others).

---

General comment: Prefer `if x {` over `if x == true {`.

### Todo's (added by florian)
1. [x] Fix the import path
2. [x] Add documentation for `HardBootstrap`
3. [x] Change the error "collection" to one error
4. [x] Add a context to the `Bootstrap` method
5. [x] Implement `io.Closer` interface
6. [x] Fix unsafe threads
7. [x] Fix synchronous bootstrap
8. [x] Refactor conditions

**Comment by florianlenz** [comment]
Thanks for the detailed review! I appreciate it. 

> Isn't this just going to end up being synchronous?

Yes and no, the `Bootstrap` function run's multiple `Connect` attempts at the same time but they all need to be done in order to return from the function. Would you like it to return from the function imminently? I found the method quite useful as it is right now. I can add a second one which is completely async.

> Should take a context.

What should be the purpose of that context / what should it do inside the function? (I am quite new to go - I will figure it our my self if you push me in the right direction)

> Calling this multiple times on every disconnect is going to be a bit slow (lots of copying). I'd recommend tracking connects and disconnects with a counter (although we might want to consider adding some kind of Size() method to the Network interface).

Yeah make sense. I can implement that method in the Network If we should have it anyway. I can also use the amount of connected peer's as a reference to avoid the unnecessary memory usage. What do you prefere / do you have another idea?

**Comment by Stebalien** [comment]
> Yes and no, the Bootstrap function run's multiple Connect attempts at the same time but they all need to be done in order to return from the function. Would you like it to return from the function imminently? I found the method quite useful as it is right now. I can add a second one which is completely async.

I agree that they should finish before returning (well, really, we only need *one* to succeed). However, the way that loop is written, it will call connect sequentially instead of in parallel (blocking on the channel read (`<-c`)).

>> Should take a context.

> What should be the purpose of that context / what should it do inside the function? (I am quite new to go - I will figure it our my self if you push me in the right direction)

Contexts are used for cancellation, timeouts, and request metadata. In this case, we care most about cancellation/timeouts. `Bootstrap` would be defined as `Bootstrap(ctx context.Context) error` and it would pass this context down to each `Connect` call instead of using the background context. That way, if the user decides that they don't actually need to bootstrap, the bootstrap process will be aborted.

> Yeah make sense. I can implement that method in the Network If we should have it anyway.

Hold off on that one for now, I'm in the middle of refactoring Network.

**Comment by florianlenz** [comment]
All right, I did some refactoring. Could you please checkout the [refactoring branch](https://github.com/florianlenz/go-libp2p-bootstrap/tree/refactoring)?

The main change is that I switched to goroutines for state management (I think my approach is a bid over engineered - what do you think?). I also changed the bootstrap logic to be a forever running go routine that bootstrap when certain conditions are given. Can you also please check if the I use the `context` in the right way? I wonder if it's correct how I use it (I am just passing it down the the connect function). 

Thank you for you help :)

**Comment by florianlenz** [comment]
ping @Stebalien

**Comment by florianlenz** [comment]
I am closing the issue. Feel free to open it again if there are still concerns.

**Comment by Stebalien** [comment]
Sorry, I've been non-stop traveling. I'll try to take a look at this soon.

**Comment by florianlenz** [comment]
No problem. Take your time :)
